name: do_an
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  http: ^0.13.6
  shared_preferences: ^2.0.11

flutter:
  uses-material-design: true

  # Thêm phần assets đúng chỗ
  assets:
    - assets/images/logo_intro.png
    - assets/images/text_intro.png
    - assets/images/fill.png
    - assets/images/circle.png
    - assets/images/status_bar.png
    - assets/icons/google_icon.png
    - assets/icons/apple_icon.png
    - assets/images/avatar_profile.png
    - assets/images/email_via.png